### ISSUE TITLE
compile error on x86 and raspberry

### ISSUE THREAD

**Issue by leschNUX** [njh/owmqtt#8]
Hi,

to compile it on a nuc 64bit and raspberry, i get some issue:

./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for OW_init in -lowcapi... no
configure: error: Misssing owfs library

any ideas?

**Comment by njh** [comment]
I am not working on owmqtt anymore.

I am now using [Node-RED](https://nodered.org) and [node-red-contrib-owfs](https://flows.nodered.org/node/node-red-contrib-owfs) to send data from 1-wire to MQTT.

(but your problem might be because you don't have [libow-dev](https://packages.debian.org/stretch/libow-dev) and [libownet-dev](url
https://packages.debian.org/stretch/libownet-dev) installed).
